name: Inspect Git behaviour wrt newlines
on:
  push:

jobs:
  checkout:
    runs-on: windows-latest
    steps:
      - name: Inspect the git config
        run: |
          git config --get core.autocrlf
