name: Run LLDB tests on macOS
on:
  push:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew install ninja swig
          pip install psutil packaging
      - uses: actions/checkout@v4
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: 1000M
          key: lldb
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../llvm \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_TARGETS_TO_BUILD="X86;AArch64" \
            -DLLVM_ENABLE_PROJECTS="clang;lld;lldb" \
            -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DPython3_EXECUTABLE=$(which python) \
            -DLLVM_LIT_ARGS="-v --time-tests"
          ninja lldb-test-depends
      - name: Run tests
        run: |
          cd build
          ninja check-lldb
