name: Build and Test on Windows
on:
  push:
    paths:
      - '.github/workflows/windows-test.yaml'
  pull_request:
    paths:
      - '.github/workflows/windows-test.yaml'

permissions:
  contents: read # Default everything to read-only

jobs:
  msvc:
    runs-on: windows-2022
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install psutil
      - name: Set up the MSVC dev environment
        uses: ilammy/msvc-dev-cmd@v1
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: 2G
          key: clangcl
          variant: sccache
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../llvm `
            -G Ninja `
            -DCMAKE_BUILD_TYPE=Release `
            -DLLVM_ENABLE_PROJECTS="clang;lld;clang-tools-extra" `
            -DCMAKE_C_COMPILER=clang-cl `
            -DCMAKE_CXX_COMPILER=clang-cl `
            -DCMAKE_C_COMPILER_LAUNCHER=sccache `
            -DCMAKE_CXX_COMPILER_LAUNCHER=sccache `
            -DPython3_FIND_REGISTRY=LAST `
            -DLLVM_LIT_ARGS="-v --time-tests"
          # --timeout=1500
          ninja test-depends
      - name: Run tests
        run: |
          cd build
          ninja check

  mingw:
    runs-on: windows-2022
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          choco install ninja
      - name: Install toolchain
        run: |
          curl -LO https://github.com/mstorsjo/llvm-mingw/releases/download/20240502/llvm-mingw-20240502-ucrt-x86_64.zip
          Expand-Archive llvm-mingw-*.zip -DestinationPath .
          del llvm-mingw-*.zip
          mv llvm-mingw-* c:\llvm-mingw
          echo "c:\llvm-mingw\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
          echo "c:\llvm-mingw\python\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
          echo "PYTHON_EXE=c:/llvm-mingw/python/bin/python3.exe" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: 2G
          key: mingw
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ../llvm `
            -G Ninja `
            -DCMAKE_BUILD_TYPE=Release `
            -DLLVM_ENABLE_PROJECTS="clang;lld;clang-tools-extra" `
            -DLLVM_WINDOWS_PREFER_FORWARD_SLASH=OFF `
            -DCMAKE_C_COMPILER=clang `
            -DCMAKE_CXX_COMPILER=clang++ `
            -DCMAKE_C_COMPILER_LAUNCHER=ccache `
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache `
            -DLLVM_LIT_ARGS="-v --time-tests"
          ninja test-depends
      - name: Run tests
        run: |
          cd build
          ninja check
